version: '3.1'
services:

    redis:
        image: 'redis:5.0.5'
        command: redis-server --requirepass redispass

    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - ./volume/postgres:/var/lib/postgresql/data/pgdata
        ports:
            - "5432:5432"

    webserver:
        build:
            context: ./docker/airflow
        image: docker-airflow:1.0.0
        restart: always
        user: root
        depends_on:
            - postgres
            - redis
        environment:
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - LOAD_EX=n
            - EXECUTOR=Celery
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
            - REDIS_PASSWORD=redispass
        volumes:
            - ./docker/airflow/dags:/usr/local/airflow/dags
            - ./docker/airflow/config/airflow.cfg:/usr/local/airflow/airflow.cfg
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

    flower:
        build:
            context: ./docker/airflow
        image: docker-airflow:1.0.0
        restart: always
        depends_on:
            - redis
        environment:
            - EXECUTOR=Celery
            - REDIS_PASSWORD=redispass
        ports:
            - "5555:5555"
        command: celery flower

    scheduler:
        build:
            context: ./docker/airflow
        image: docker-airflow:1.0.0
        user: root
        restart: always
        depends_on:
            - webserver
        volumes:
            - ./docker/airflow/dags:/usr/local/airflow/dags
            - ./docker/airflow/config/airflow.cfg:/usr/local/airflow/airflow.cfg
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            - LOAD_EX=n
            - EXECUTOR=Celery 
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
            - REDIS_PASSWORD=redispass
        command: scheduler

    worker:
        build:
            context: ./docker/airflow
        image: docker-airflow:1.0.0
        restart: always
        privileged: true
        user: root
        depends_on:
            - scheduler
        volumes:
            - ./docker/airflow/dags:/usr/local/airflow/dags
            - ./docker/airflow/config/airflow.cfg:/usr/local/airflow/airflow.cfg
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
            - REDIS_PASSWORD=redispass
        command: celery worker